### ISSUE TITLE
Preparing first stable release

### ISSUE THREAD

**Issue by machour** [yiisoft/yii2-bootstrap4#84]
This extension seems almost ready and is already totaling ~20k downloads :)
We should probably publish a first stable release into the wild and see how it plays.

We still need to:
- [x] Document some stuff: #25, #81, #83 
- [x] Fix two layout problems: #36, #78 
- [x] Switch to npm: #35 (PR #40)
- [x] #85 update dependency versions

@simialbi do you have the time to look at the open issues? (no pressure)

**Comment by samdark** [comment]
Documentation issues left...

**Comment by samdark** [comment]
And https://github.com/yiisoft/yii2-bootstrap4/pull/85

**Comment by samdark** [comment]
Also I think it worth taking a look at https://github.com/yiisoft/yii2-bootstrap/milestones/2.1

**Comment by machour** [comment]
Worth considering for first release as these would break BC later

- [ ] https://github.com/yiisoft/yii2-bootstrap/pull/57
- [ ] https://github.com/yiisoft/yii2-bootstrap/pull/76

**Comment by samdark** [comment]
These can't be moved so the only way it to re-apply these to code in this repository.

**Comment by machour** [comment]
@simialbi interested on your take about the remaining items in the old 2.1 milestone: https://github.com/yiisoft/yii2-bootstrap/milestones/2.1

**Comment by simialbi** [comment]
There are still 4 items:
 * https://github.com/yiisoft/yii2-bootstrap/issues/164: I recommend not to realise this. The current class fulfills all the variants described by the documentation. Anything going further has to be customized by application, not library.
 * https://github.com/yiisoft/yii2-bootstrap/issues/147: Could be realised, but would break BC. As you already mentioned, there are already 20k installs...
 * https://github.com/yiisoft/yii2-bootstrap/issues/101: Could easily be realised but would change current behavior. For me it's ok. @samdark ? @machour ? What do you think ? (Code Reference: https://github.com/simialbi/yii2-bootstrap4/blob/69d8b7779f7983d1b5768110d0e7c58ba723a96c/src/NavBar.php#L139)
 * https://github.com/yiisoft/yii2-bootstrap/issues/16: For me this makes no sense. As mentioned in issue, Nav extens Bootstrap Widget because of Bootstrap functionality. In addition the behavior of Menu and Nav are not equal. **Sub navigations** in `Nav` are `Dropdown`s in `Menu` they're still `Menu`s

**Comment by samdark** [comment]
We haven't tagged release so BC breaks are still OK.

**Comment by simialbi** [comment]
@samdark about https://github.com/yiisoft/yii2-bootstrap/issues/147:
There is still another poblem: `yii\bootstrap4\ActiveField` extends `yii\widgets\ActiveField` and `yii\widgets\ActiveField` has a method called `dropDownList`. If we'd like to be consistent, we would have to change it there too.

**Comment by simialbi** [comment]
Ok, I changed my open PR #90
What about https://github.com/yiisoft/yii2-bootstrap/issues/101? Shall I add the possibility of a brand without link (`span`) instead of setting home link as default?

**Comment by samdark** [comment]
It's not bootstrap 4 specific so if you think it's a good move, feel free to.

**Comment by simialbi** [comment]
Now there is still:
 * #81 I'm not sure what's the *correct* way to do this. In my opinion this is very project specific. Sometimes you need bootstrap as base, sometimes you customize it...
 * #85 I would prefer not to change to npm. But it's up to you
> * https://github.com/yiisoft/yii2-bootstrap/issues/164: I recommend not to realise this. The current class fulfills all the variants described by the documentation. In my opinion anything going further has to be customized by application, not library.
>  * https://github.com/yiisoft/yii2-bootstrap/issues/16: For me this makes no sense. As mentioned in issue, Nav extends Bootstrap Widget because of Bootstrap functionality. In addition the behavior of Menu and Nav are not equal. **Sub navigations** in `Nav` are `Dropdown`s in `Menu` they're still `Menu`s

I think my part is finished now. In my opinion it's ready for a release now. If I can still help somewhere, just tell me...

**Comment by machour** [comment]
Thank you so much @simialbi !

#81: my initial grief was "we should not install bootstrap from npm" which is wrong. This is a docs improvement and is not blocking for the release.

#85: bower is dead. I never personally experienced the issues you're facing with npm, and have been using it with assets-packagist or foxy/foxy for months. I think it should be merged.

I agree with you for the two other issues.

**Comment by samdark** [comment]
Merged #85.

**Comment by machour** [comment]
Opened #92 & #93

**Comment by machour** [comment]
Added #95 that I'd like to discuss before the first release. Doesn't seem like much of an effort implementation wise, and comes with great benefits.

**Comment by machour** [comment]
Sadly I've been swamped with work these days.

Changes from #95 should not break BC, so I guess they could be shipped in a subsequent release.
Let's ship yii2-bootstrap4 as it is now, and enhance it later.
